// Generated by Project Workspace CLI.
import { ProjectWorkspacePage } from "@npmaccount990/project-workspace/react";


export const dynamic = "force-dynamic";

export default async function WorkspacePage() {
  return (
    <ProjectWorkspacePage
      storageKey={"workspace:shared"}
      canManageRepositories={true}
    />
  );
}
