// Generated by Project Workspace CLI.
import path from "node:path";
import { createProjectWorkspaceHandler } from "@npmaccount990/project-workspace/server";


export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const handler = createProjectWorkspaceHandler({
  apiBasePath: "/api/project-workspace",
  dataDirectory: process.env.PROJECT_WORKSPACE_DATA_DIR
    || path.join(process.cwd(), ".data", "project-workspace"),
});

export { handler as GET, handler as POST, handler as PUT, handler as DELETE };
